CREATE TABLE vehicles (
    id CHAR(36) PRIMARY KEY,
    vehicles_name VARCHAR(150),
    fipe_code VARCHAR(15),
    price DECIMAL(18,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);